### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by karjonas** [thinks/ppm-io#1]
Hi,

I  appreciate you creating this simple and useful library! I want to use it in my code but since I couldn't find any license I am not sure I can. I would suggest a license like https://github.com/nothings/stb/ is using which is a dual MIT and public domain one. It seems like your goals are similar so I think it would make sense.

Thanks, Jonas Karlsson

**Comment by thinks** [comment]
Hi,

Glad you like it. I add a generous license first week of June, when I get
back home.

T

**Comment by karjonas** [comment]
Great, Thank you!

**Comment by thinks** [comment]
Added MIT license, hope that helps.

**Comment by karjonas** [comment]
Perfect!
