### ISSUE TITLE
Compatibility with PPM images with >8 BPC?

### ISSUE THREAD

**Issue by rr-codes** [thinks/ppm-io#2]
As PPM is an arbitrary data format, it can support an arbitrary amount of bits per channel. However, this only supports PPM images with 8 BPC. Is there an easy way of modifying it to accept 10 or 16 bpc (as is common in HDR images)?

**Comment by thinks** [comment]
Not sure how "easy" it would be. There is some infrastructure for reading files and so on, but having had a quick look at the code it might be non-trivial to extend to an arbitrary BPC. This would be a nice feature to add, but not something I am looking to do right now, unfortunately. I would happily review any such attempts though.
